version: "3.4"

services:
  api:
    build:
      context: .
      target: production

    image: martinezcarballo/one_secret_app:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - IMAGE_NAME=docker.io
